### ISSUE TITLE
DontReturnDisposedInstance

### ISSUE THREAD

**Issue by Hosch250** [JohanLarsson/Gu.Analyzers#114]
One example:

    public static IReadOnlyList<EventArgs> ResetArgs()
    {
        using (var item = new Disposable())
        {
            return item;
        }
    }

Another:

    public static IReadOnlyList<EventArgs> ResetArgs()
    {
        var item = new Disposable();
        item.Dispose();
        return item;
    }

**Comment by JohanLarsson** [comment]
This issue was moved to DotNetAnalyzers/IDisposableAnalyzers#30
