### ISSUE TITLE
IDisposable proposal

### ISSUE THREAD

**Issue by Anlo2846** [JohanLarsson/Gu.Analyzers#14]
Would it be possible to check that IDisposable objects are disposed, either through the Dispose method or the using statement?

**Comment by JohanLarsson** [comment]
What rules should we have? I'm thinking:

1) Flag variables that are created with `new` or returned from function calls that are not used with `using`
2) Flag fields & properties that are created in the class and not disposed in the dispose method. `IDisposable`s passed in via ctor should not be disposed I think. Maybe we should have a warning for that?

What about a warning that nags about making `IDisposable` types sealed?

**Comment by JohanLarsson** [comment]
Think we are pretty close to something useful now. Closing this, write issues with bugs.
